# Generated by Django 3.2.3 on 2021-11-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_lessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('message', models.TextField()),
                ('email', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
